language: generic
sudo: required
services:
        - docker

before_install:
        - docker build -t geodumit/docker-react -f Dockerfile.dev .

script:
        - docker run -e CI=true geodumit/docker-react npm run test 

deploy:
        provider: elasticbeanstalk
        region: "us-east-2"
        app: "docker-react"
        env: "Dockerreact-env"
        bucket_name: "elasticbeanstalk-us-east-2-101093584702"
        bucket_path: "docker-react"
        on:
                branch: main
        access_key_id: $AWS_ACCESS_KEY
        secret_access_key: $AWS_SECRET_KEY
        edge: true
